# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ForceAbility.create(id: 0, name: 'Alter Environment')
ForceAbility.create(id: 1, name: 'Animal Bond')
ForceAbility.create(id: 2, name: 'Battlemind')
ForceAbility.create(id: 3, name: 'Combustion')
ForceAbility.create(id: 4, name: 'Crucitorn')
ForceAbility.create(id: 5, name: 'Dark Transfer')
ForceAbility.create(id: 6, name: 'Droid Disable')
ForceAbility.create(id: 7, name: 'Electric Judgement')
ForceAbility.create(id: 8, name: 'Force Blinding')
ForceAbility.create(id: 9, name: 'Force Enlightenment')
ForceAbility.create(id: 10, name: 'Force Healing')
ForceAbility.create(id: 11, name: 'Force Ghost')
ForceAbility.create(id: 12, name: 'Force Light')
ForceAbility.create(id: 13, name: 'Force Orb')
ForceAbility.create(id: 14, name: 'Force Projection')
ForceAbility.create(id: 15, name: 'Force Protection')
ForceAbility.create(id: 16, name: 'Force Stun')
ForceAbility.create(id: 17, name: 'Force Valor')
ForceAbility.create(id: 18, name: 'Hibernation Trance')
ForceAbility.create(id: 19, name: 'Levitation')
ForceAbility.create(id: 20, name: 'Mind Trick')
ForceAbility.create(id: 21, name: 'Malacia')
ForceAbility.create(id: 22, name: 'Morichro')
ForceAbility.create(id: 23, name: 'Transfer Force')
ForceAbility.create(id: 24, name: 'Plant Surge')
ForceAbility.create(id: 25, name: 'Precognition')
ForceAbility.create(id: 26, name: 'Revitalize')
ForceAbility.create(id: 27, name: 'Dark Energy Trap')
ForceAbility.create(id: 28, name: 'Darksight')
ForceAbility.create(id: 29, name: 'Deadly Sight')
ForceAbility.create(id: 30, name: 'Drain Knowledge')
ForceAbility.create(id: 31, name: 'Fiery Destruction')
ForceAbility.create(id: 32, name: 'Force Drain')
ForceAbility.create(id: 33, name: 'Force Fear')
ForceAbility.create(id: 34, name: 'Force Lightning')
ForceAbility.create(id: 35, name: 'Force Maelstrom')
ForceAbility.create(id: 36, name: 'Force Phantom')
ForceAbility.create(id: 37, name: 'Force Rage')
ForceAbility.create(id: 38, name: 'Force Scream')
ForceAbility.create(id: 39, name: 'Force Slow')
ForceAbility.create(id: 40, name: 'Force Sphere')
ForceAbility.create(id: 41, name: 'Force Storm')
ForceAbility.create(id: 42, name: 'Force Wound')
ForceAbility.create(id: 43, name: 'Force Choke')
ForceAbility.create(id: 44, name: 'Kinetite')
ForceAbility.create(id: 45, name: 'Mechu-deru')
ForceAbility.create(id: 46, name: 'Midi-chlorian Manipulation')
ForceAbility.create(id: 47, name: 'Mind Control')
ForceAbility.create(id: 48, name: 'Sith Alchemy')
ForceAbility.create(id: 49, name: 'Spear of Midnight Black')
ForceAbility.create(id: 50, name: 'Spirit Transference')
ForceAbility.create(id: 51, name: 'Sutta Chwituskak')
ForceAbility.create(id: 52, name: 'Thought Bomb')
ForceAbility.create(id: 53, name: 'Torture by Chagrin')
ForceAbility.create(id: 54, name: 'Waves of Darkness')
ForceAbility.create(id: 55, name: 'Telekinesis')

ForceUser.create(name: 'Emperor Palpatine', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 34 )
ForceUser.create(name: 'Darth Vader', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 43 )
ForceUser.create(name: 'Darth Maul', team: 'Sith', gender: 'Male', race: 'Zabrak', force_ability_id: 43 )
ForceUser.create(name: 'Darth Revan', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 55 )
ForceUser.create(name: 'Darth Malak', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 34 )
ForceUser.create(name: 'Darth Malgus', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 37 )
ForceUser.create(name: 'Darth Ruin', team: 'Sith', gender: 'Male', race: 'Umbaran', force_ability_id: 34 )
ForceUser.create(name: 'Darth Bane', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 32 )
ForceUser.create(name: 'Darth Andeddu', team: 'Sith', gender: 'Male', race: 'Humanoid', force_ability_id: 34 )
ForceUser.create(name: 'Darth Plagueis', team: 'Sith', gender: 'Male', race: 'Muu ', force_ability_id: 46 )

ForceUser.create(name: 'Qui-Gon Jinn', team: 'Jedi', gender: 'Male', race: 'Human', force_ability_id: 11 )
ForceUser.create(name: 'Obi-Wan Kenobi', team: 'Jedi', gender: 'Male', race: 'Human', force_ability_id: 11 )
ForceUser.create(name: 'Cal Kestis', team: 'Jedi', gender: 'Male', race: 'Human', force_ability_id: 55 )
ForceUser.create(name: 'Rey Skywalker', team: 'Jedi', gender: 'Female', race: 'Human', force_ability_id: 10 )