# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ForceAbility.create(name: 'Dark Transfer')
ForceAbility.create(name: 'Droid Disable')
ForceAbility.create(name: 'Electric Judgement')
ForceAbility.create(name: 'Force Blinding')
ForceAbility.create(name: 'Force Enlightenment')
ForceAbility.create(name: 'Force Healing')
ForceAbility.create(name: 'Force Ghost')
ForceAbility.create(name: 'Force Light')
ForceAbility.create(name: 'Force Orb')
ForceAbility.create(name: 'Force Projection')
ForceAbility.create(name: 'Force Protection')
ForceAbility.create(name: 'Force Stun')
ForceAbility.create(name: 'Force Valor')
ForceAbility.create(name: 'Hibernation Trance')
ForceAbility.create(name: 'Levitation')
ForceAbility.create(name: 'Mind Trick')
ForceAbility.create(name: 'Malacia')
ForceAbility.create(name: 'Morichro')
ForceAbility.create(name: 'Transfer Force')
ForceAbility.create(name: 'Plant Surge')
ForceAbility.create(name: 'Precognition')
ForceAbility.create(name: 'Revitalize')
ForceAbility.create(name: 'Dark Energy Trap')
ForceAbility.create(name: 'Darksight')
ForceAbility.create(name: 'Deadly Sight')
ForceAbility.create(name: 'Drain Knowledge')
ForceAbility.create(name: 'Fiery Destruction')
ForceAbility.create(name: 'Force Drain')
ForceAbility.create(name: 'Force Fear')
ForceAbility.create(name: 'Force Lightning')
ForceAbility.create(name: 'Force Maelstrom')
ForceAbility.create(name: 'Force Phantom')
ForceAbility.create(name: 'Force Rage')
ForceAbility.create(name: 'Force Scream')
ForceAbility.create(name: 'Force Slow')
ForceAbility.create(name: 'Force Sphere')
ForceAbility.create(name: 'Force Storm')
ForceAbility.create(name: 'Force Wound')
ForceAbility.create(name: 'Force Choke')
ForceAbility.create(name: 'Kinetite')
ForceAbility.create(name: 'Mechu-deru')
ForceAbility.create(name: 'Midi-chlorian Manipulation')
ForceAbility.create(name: 'Mind Control')
ForceAbility.create(name: 'Sith Alchemy')
ForceAbility.create(name: 'Spear of Midnight Black')
ForceAbility.create(name: 'Spirit Transference')
ForceAbility.create(name: 'Sutta Chwituskak')
ForceAbility.create(name: 'Thought Bomb')
ForceAbility.create(name: 'Torture by Chagrin')
ForceAbility.create(name: 'Waves of Darkness')

ForceUser.create(name: 'Emperor Palpatine', team: 'Sith', gender: 'Male', race: 'Human', force_ability_id: 1 )